spring.application.name=logistick
server.port=${PORT:8080}
spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:logstickproject}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:root}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

